Repository WSU-4110/Travel-Companion, pull requests merged in 2024-04, with the labels that each got.

#81 Add the ability to save parts of a trip
  src/api/databaseManager.js
  src/components/ConfirmDelete.vue
  src/components/TripSelector.vue
  src/main.js
  src/views/TranslatorView.vue
Labels: Feature

#84 Fixed Translator Bug issue
  src/main.js
  src/views/TranslatorView.vue
Labels: bug

#92 Added Save Location Functionality
  src/main.js
  src/views/HomeView.vue
  src/views/UserLocation.vue
Labels: FR, Feature

#97 Added Weather Page Map Functionality
  src/main.js
  src/views/UserLocation.vue
  src/views/Weather.vue
Labels: FR, Feature
