Repository WSU-4110/Travel-Companion, pull requests merged in 2024-03, with the labels that each got.

#57 Add translation key to AWS
  src/App.vue
  src/api/userVerification.js
  src/main.js
Labels: task

#62 Adding API key
  src/views/TranslatorView.vue
Labels: FR, Feature

#61 Begin using the adapter design pattern
  installation.md
  src/App.vue
  src/api/databaseManager.js
  src/api/userVerification.js
  src/components/Sidebar.vue
  src/components/TripSelector.vue
  src/main.js
  src/router/index.js
  src/views/SignInSignUpView.vue
  src/views/TripManagerView.vue
Labels: Feature

#64 Bug Fix for Currency Exchange and Add FetchLanguages to Translator
  README.md
  src/views/CurrencyExchange.vue
  src/views/TranslatorView.vue
Labels: bug, FR, Feature

#70 Fixed Translator form select issue, Added Saving Translations, Touched up about us page
  src/views/AboutUs.vue
  src/views/TranslatorView.vue
Labels: bug, FR, Feature
